server:
  port: 8095

springjpa:
  hibernate:
    ddl-auto: update
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shop
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver


---
spring.pprifies: dev

spring:
  datasource:
    url: jdbc:mysql://database-2.cyu1f8uvzgh9.us-east-2.rds.amazonaws.com:3306/shop
    username: masterUsername
    password: Federer7$
    driver-class-name: com.mysql.cj.jdbc.Driver
